### ISSUE TITLE
make pdf_rendering work

### ISSUE THREAD

**Issue by petermeissner** [petermeissner/crossword.r#7]

**Comment by Christian-T** [comment]
Hello Peter and thanks for your nice function :)
I'd like to use it for a small project; however I did not manage to get the pdf_rendering to work. I found out the following functions should be a bit different (need to access private method of cw object via cw$.__enclos_env__$private$...). Furthermore I couldn't find the function cw_words_add_id(). Could you provide me with it?

```
cw_glue_puzzle <- function(cw){
   glue::glue(
     .open = "<R>",
     .close = "</R>",
     columns = cw$.__enclos_env__$private$columns,
     rows    = cw$.__enclos_env__$private$rows,
   "
 \\definecolor{gray}{gray}{.95}
 \\PuzzleDefineColorCell{g}{gray}
 \\begin{Puzzle}{<R>columns</R>}{<R>rows</R>}
 <R>
 cw_glue_table(cw$letters)
 </R>
 \\end{Puzzle}
 ")
 }


 cw_glue_solution <- function(cw){
   glue::glue(
     .open="<R>",
     .close="</R>",
 "\\newpage
 \\PuzzleSolution
 \\begin{Puzzle}{<R>cw$.__enclos_env__$private$columns</R>}{<R>cw$.__enclos_env__$private$rows</R>}
 <R>cw_glue_table(cw$letters)</R>
 \\end{Puzzle}
 \\end{document}
 "
   )
 }
```

**Comment by petermeissner** [comment]
Hey, thanks for writing in. 

I am having a hard time understanding your question. Can you make it more readable (help me help you) - e.g. format code as code, have a look here: https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax? 

Anyhow, most likely the answer is no. No, pdf rendering is not working that is why this issue still is open and I currently have no time/plans to make it work - sorry.

**Comment by Christian-T** [comment]
Hi, thanks for your quick reply. Sorry for the bad structure; I formatted it as code now. I meant that firstly your methods `cw_glue_puzzle()` and `cw_glue_solution()` did not work for me, but with the above mentioned code, they do work. `cw` is a R6 object, that has some `public` and some `private` methods, and `rows` and `columns` are private, which is why we (at least I) need to access it via this complicated `cw$.enclos_env$private$...`-part. Secondly, your function `cw_glue_clues()` refers to another function called `cw_words_add_id()` which seems to add an id column ;) . However, I could not find this function in your repo; maybe you have stored it locally somewhere?

If pdf rendering will not work, could you hint me what to do with the json code, to get a nicely formatted crossword? Do I need to paste it on a webpage? Unfortunately, I am not familiar with json.
Thanks in advance!

**Comment by petermeissner** [comment]
Yeah, I see now.

Look, the code in ./rendering is all commented out - this is for a reason.
This was a try, an experiment, It did not work. In the last 2 years I did
not find neither time nor motivation to work on the problem. I will not
invest any time on this, nor do I have time to support questions on
abandoned code - consider ./rendering as non-existent as far as I am
concerned. Most likely the code in ./rendering is very much out of sync
with the rest of the package. I think I switched from a more function
oriented to object oriented programming solution - browse the git history
if you care to find out what happened.

I did not find the function you were asking for, most likely it was there
once and got refactored away along the way.

If you find a way to make this work, please do make a pull request - (Fork
the repo, make a new branch, solve the problem, document your code, pass R
CMD check, open pull request).

Private fields and methods are most likely private to not expose data/logic
that should not be tempered with or which I do not like to support.
Therefore, I see no reason to expose them.

Sorry, but this package is pretty much as-is as far as I am concerned. But
since it's open source you can of course fork it and work on it under the
terms of the licence agreement.

Best, Peter



Am Di., 13. Okt. 2020 um 09:47 Uhr schrieb Christian-T <
notifications@github.com>:

**Comment by petermeissner** [comment]
Also, please do your homework. 

The official example from the documentation does already provide the information you are trying to forcefully extract from the crossword object, see `?Crossword` , section Examples.
